In [1]:
from transformers import BertTokenizer, BertModel
import numpy as np
import torch

tokenizer = BertTokenizer.from_pretrained('./test/saved_model/vocab.txt')

bert = BertModel.from_pretrained('./test/saved_model/')

s = "I'm not sure, this can work, lol -.-"

tokens = tokenizer.tokenize(s)
print("\\".join(tokens))
# "i\\'\\m\\not\\sure\\,\\this\\can\\work\\,\\lo\\##l\\-\\.\\-"
# 是否需要这样做？
# tokens = ["[CLS]"] + tokens + ["[SEP]"]

ids = torch.tensor([tokenizer.convert_tokens_to_ids(tokens)])
print(ids.shape)
# torch.Size([1, 15])

result = bert(ids, output_hidden_states=True)
print(result)

/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/transformers/tokenization_utils_base.py:1631: FutureWarning: Calling BertTokenizer.from_pretrained() with the path to a single file or url is deprecated and won't be possible anymore in v5. Use a model identifier or the path to a directory instead.
  FutureWarning,


i\'\m\not\sure\,\this\can\work\,\lo\##l\-\.\-
torch.Size([1, 15])
BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 0.1559,  0.0427,  0.2496,  ..., -0.3521,  0.1700,  0.4932],
         [ 0.3662,  0.3600,  0.6951,  ..., -0.4676,  0.1914,  0.3500],
         [ 0.3161,  0.4953,  0.3921,  ..., -0.5428,  0.2684,  1.3029],
         ...,
         [ 0.4199,  0.1679,  0.5940,  ..., -0.1377,  0.1986,  0.4219],
         [ 0.1325, -0.1673,  0.6549,  ..., -0.0030,  0.5450,  0.3319],
         [ 0.3377, -0.0386,  1.0407,  ..., -0.0521,  0.5324,  0.7737]]],
       grad_fn=<NativeLayerNormBackward>), pooler_output=tensor([[-6.3580e-01,  2.9413e-03,  6.0078e-01,  3.9510e-01, -3.8253e-01,
         -3.5963e-02,  4.5680e-01,  1.1072e-01,  8.0616e-01, -9.7523e-01,
          6.8483e-01, -2.9353e-01,  9.5688e-01, -6.6352e-01,  9.3670e-01,
         -4.7479e-02,  1.2822e-01, -3.6295e-01,  6.7251e-02, -1.9408e-01,
          7.5842e-01,  7.7572e-01,  7.3900e-01,  5.8289e-02,  1.0056e-01,
  

In [9]:
print(len(tokens))

15


In [5]:
print(len(result))

3


In [8]:
print(result[0].shape)

torch.Size([1, 15, 768])


In [10]:
print(result[1].shape)

torch.Size([1, 768])


In [14]:
print(len(result[2]))

13


In [20]:
[x.shape for x in result[2]]

[torch.Size([1, 15, 768]),
 torch.Size([1, 15, 768]),
 torch.Size([1, 15, 768]),
 torch.Size([1, 15, 768]),
 torch.Size([1, 15, 768]),
 torch.Size([1, 15, 768]),
 torch.Size([1, 15, 768]),
 torch.Size([1, 15, 768]),
 torch.Size([1, 15, 768]),
 torch.Size([1, 15, 768]),
 torch.Size([1, 15, 768]),
 torch.Size([1, 15, 768]),
 torch.Size([1, 15, 768])]

In [15]:
print(result[2][12])

tensor([[[ 0.1559,  0.0427,  0.2496,  ..., -0.3521,  0.1700,  0.4932],
         [ 0.3662,  0.3600,  0.6951,  ..., -0.4676,  0.1914,  0.3500],
         [ 0.3161,  0.4953,  0.3921,  ..., -0.5428,  0.2684,  1.3029],
         ...,
         [ 0.4199,  0.1679,  0.5940,  ..., -0.1377,  0.1986,  0.4219],
         [ 0.1325, -0.1673,  0.6549,  ..., -0.0030,  0.5450,  0.3319],
         [ 0.3377, -0.0386,  1.0407,  ..., -0.0521,  0.5324,  0.7737]]],
       grad_fn=<NativeLayerNormBackward>)


In [16]:
print(result[0])

tensor([[[ 0.1559,  0.0427,  0.2496,  ..., -0.3521,  0.1700,  0.4932],
         [ 0.3662,  0.3600,  0.6951,  ..., -0.4676,  0.1914,  0.3500],
         [ 0.3161,  0.4953,  0.3921,  ..., -0.5428,  0.2684,  1.3029],
         ...,
         [ 0.4199,  0.1679,  0.5940,  ..., -0.1377,  0.1986,  0.4219],
         [ 0.1325, -0.1673,  0.6549,  ..., -0.0030,  0.5450,  0.3319],
         [ 0.3377, -0.0386,  1.0407,  ..., -0.0521,  0.5324,  0.7737]]],
       grad_fn=<NativeLayerNormBackward>)


In [18]:
print(result[2][12] == result[0])

tensor([[[True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         ...,
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True]]])


##  Frozen Layer 

In [2]:
for name, param in bert.named_parameters():                                            
    print(name)

embeddings.word_embeddings.weight
embeddings.position_embeddings.weight
embeddings.token_type_embeddings.weight
embeddings.LayerNorm.weight
embeddings.LayerNorm.bias
encoder.layer.0.attention.self.query.weight
encoder.layer.0.attention.self.query.bias
encoder.layer.0.attention.self.key.weight
encoder.layer.0.attention.self.key.bias
encoder.layer.0.attention.self.value.weight
encoder.layer.0.attention.self.value.bias
encoder.layer.0.attention.output.dense.weight
encoder.layer.0.attention.output.dense.bias
encoder.layer.0.attention.output.LayerNorm.weight
encoder.layer.0.attention.output.LayerNorm.bias
encoder.layer.0.intermediate.dense.weight
encoder.layer.0.intermediate.dense.bias
encoder.layer.0.output.dense.weight
encoder.layer.0.output.dense.bias
encoder.layer.0.output.LayerNorm.weight
encoder.layer.0.output.LayerNorm.bias
encoder.layer.1.attention.self.query.weight
encoder.layer.1.attention.self.query.bias
encoder.layer.1.attention.self.key.weight
encoder.layer.1.attention.self.key

In [3]:
for param in bert.parameters():
    param.requires_grad = False

In [9]:
for name, param in bert.named_parameters():
    if param.requires_grad == True:
        print(name) 

In [2]:
len(list(bert.parameters()))

199